fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.2
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile.git
      ref: 1.1.2
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
  symlinks:
    php_config: "#{source_dir}"
